In [1]:
import numpy as np

In [2]:
p = np.array([2, 4, 5])
v = np.array([8, 10, 2])
s = np.array([0, 12, 7])

In [3]:
500*p + 100*v + 0*s

array([1800, 3000, 2700])

#### Task 1.
Найдите линейную комбинацию векторов 
$\vec{x}=\begin{pmatrix}4\\ 5\\ \end{pmatrix}, \vec{y}=\begin{pmatrix}2\\ 1\\ \end{pmatrix}, \vec{u}=\begin{pmatrix}1\\ 0\\ \end{pmatrix}$
с коэффициентами 2, 3 и 5.

In [4]:
x = np.array([4, 5])
y = np.array([2, 1])
u = np.array([1, 0])

In [5]:
2*x - 3*y + 5*u

array([7, 7])

#### Task 2.
Юный предприниматель Вовочка мастерит ракеты на водном топливе и продает их. За 4 недели он смастерил 3, 4, 5 и 9 ракет, а продал 1, 5, 3 и 6 ракет соответственно.

На изготовление одной ракеты он тратит 200 рублей, а продаёт их по 400 рублей за штуку.

Найдите вектор прибыли Вовочки за эти 4 недели.

In [7]:
a = np.array([3, 4, 5, 9])
b = np.array([1, 5, 3, 6])
400*b - 200*a

array([-200, 1200,  200,  600])