In [1]:
import numpy as np

In [2]:
A = np.matrix('1, 2, 3; 4, 5, 6; 7, 8, 10')

In [4]:
A

matrix([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8, 10]])

In [5]:
A_ = np.linalg.inv(A)

In [6]:
A_

matrix([[-0.66666667, -1.33333333,  1.        ],
        [-0.66666667,  3.66666667, -2.        ],
        [ 1.        , -2.        ,  1.        ]])

In [7]:
A_@A

matrix([[ 1.00000000e+00,  5.32907052e-15,  5.32907052e-15],
        [-2.22044605e-15,  1.00000000e+00, -2.66453526e-15],
        [-5.55111512e-16, -8.88178420e-16,  1.00000000e+00]])

In [9]:
A@A_

matrix([[ 1.00000000e+00, -4.44089210e-16, -1.11022302e-16],
        [ 4.44089210e-16,  1.00000000e+00, -2.22044605e-16],
        [ 4.44089210e-16,  8.88178420e-16,  1.00000000e+00]])

#### Task 3.
Обратная матрица к матрице A:
* Целочисленна
* Симметрична
* Не существует 

In [12]:
A = np.array([[1, 2],
              [2, 5]])

In [13]:
np.linalg.inv(A)

array([[ 5., -2.],
       [-2.,  1.]])

#### Task 4.
Вычислите обратную матрицу к матрице A

In [14]:
# Ужо