In [1]:
import numpy as np

In [13]:
A = np.array([
    [4, 7],
    [5, 10],
])

In [14]:
A

array([[ 4,  7],
       [ 5, 10]])

In [16]:
b = np.array([20, 30]).reshape((2, 1))

In [17]:
b

array([[20],
       [30]])

In [18]:
A_ = np.linalg.inv(A)

In [19]:
xy = A_@b

In [20]:
xy

array([[-2.],
       [ 4.]])