In [1]:
import numpy as np

In [2]:
from numpy import linalg as LA

In [3]:
A = np.array([
    [1, 2, 3],
    [3, 2, 1],
    [1, 0, -1]
])

In [4]:
val, vec = LA.eig(A)

In [5]:
val

array([ 4.31662479e+00, -2.31662479e+00,  1.47314580e-16])

In [6]:
vec

array([[ 0.58428153,  0.73595785,  0.40824829],
       [ 0.80407569, -0.38198836, -0.81649658],
       [ 0.10989708, -0.55897311,  0.40824829]])

In [7]:
u = vec[:, 0]

In [8]:
u

array([0.58428153, 0.80407569, 0.10989708])

In [12]:
A = np.array([
    [7, 2],
    [1, 8]
])

In [15]:
A

array([[7, 2],
       [1, 8]])

In [16]:
val, vec = LA.eig(A)

In [17]:
vec

array([[-0.89442719, -0.70710678],
       [ 0.4472136 , -0.70710678]])

In [18]:
val

array([6., 9.])

In [19]:
A = np.array([
    [-7, 6],
    [-12, 11]
])

In [20]:
val, vec = LA.eig(A)

In [21]:
val

array([-1.,  5.])

In [22]:
vec

array([[-0.70710678, -0.4472136 ],
       [-0.70710678, -0.89442719]])

In [23]:
A = np.array([
    [5, 1],
    [1, 5]
])

In [24]:
val, vec = LA.eig(A)

In [25]:
val

array([6., 4.])

In [26]:
vec

array([[ 0.70710678, -0.70710678],
       [ 0.70710678,  0.70710678]])