In [1]:
import numpy as np

In [2]:
# произведение матриц
A=np.random.randint(5, 12, (3,3))
B=np.random.randint(-2, 4, (3,3))

In [3]:
A

array([[ 9, 11,  8],
       [ 8, 11, 11],
       [ 6, 11, 11]])

In [4]:
B

array([[ 1,  2,  0],
       [-1,  2, -1],
       [-2,  3,  2]])

In [5]:
# Поэлементное умножение
A*B

array([[  9,  22,   0],
       [ -8,  22, -11],
       [-12,  33,  22]])

In [6]:
# тип np.matrix
A_m=np.matrix(A)
B_m=np.matrix(B)
print(A_m*B_m)

[[-18  64   5]
 [-25  71  11]
 [-27  67  11]]


In [7]:
# Матричное умножение
np.dot(A,B)

array([[-18,  64,   5],
       [-25,  71,  11],
       [-27,  67,  11]])

In [8]:
# Матричное умножение
A@B

array([[-18,  64,   5],
       [-25,  71,  11],
       [-27,  67,  11]])

In [9]:
# Порядок умножения AB != BA
B@A

array([[25, 33, 30],
       [ 1,  0,  3],
       [18, 33, 39]])

In [10]:
# Умножение прямоугольных матриц возможно не в любом порядке
A=np.random.randint(5, 12, (3,5))
B=np.random.randint(-2, 4, (5,2))
print('A:\n',A)
print('B:\n',B)

A:
 [[ 5  9  6  8  6]
 [ 5 11  9 10  6]
 [11  7  6  9  5]]
B:
 [[ 0 -2]
 [ 0  1]
 [ 0  1]
 [ 3  0]
 [ 1  3]]


In [11]:
# Умножение прямоугольных матриц возможно не в любом порядке
A@B

array([[30, 23],
       [36, 28],
       [32,  6]])

In [12]:
# Умножение прямоугольных матриц возможно не в любом порядке
B@A

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 2)

In [13]:
# размер произведения матриц
print('shape of A:', np.shape(A))
print('shape of B:', np.shape(B))
print('shape of AB:', np.shape(A@B))

shape of A: (3, 5)
shape of B: (5, 2)
shape of AB: (3, 2)


In [14]:
# умножение на специальные матрицы
A=np.random.randint(-4, 4, (4,4))
D=np.diag([1,2,0,-1])
print('A:\n',A)
print('D:\n',D)
print('AD:\n',A@D)
print('DA:\n',D@A)

A:
 [[ 1 -1  1 -4]
 [-1 -2 -4 -4]
 [-2  1 -1  0]
 [ 2  0 -4 -2]]
D:
 [[ 1  0  0  0]
 [ 0  2  0  0]
 [ 0  0  0  0]
 [ 0  0  0 -1]]
AD:
 [[ 1 -2  0  4]
 [-1 -4  0  4]
 [-2  2  0  0]
 [ 2  0  0  2]]
DA:
 [[ 1 -1  1 -4]
 [-2 -4 -8 -8]
 [ 0  0  0  0]
 [-2  0  4  2]]


In [15]:
# умножение на одномерный массив numpy
A=np.array([[1,0,1],[1,1,1]])
b=np.array([-3,4,5])
A@b

array([2, 6])

In [16]:
b@A

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 3)

In [17]:
# матрица Грама ортогональной системы векторов
x=np.array([1,1,1])
y=np.array([1,0,-1])
z=np.array([-1,2,-1])
A=np.array([x,y,z])
print (A, type(A))

[[ 1  1  1]
 [ 1  0 -1]
 [-1  2 -1]] <class 'numpy.ndarray'>


In [18]:
# матрица Грама ортогональной системы векторов
A@A.T

array([[3, 0, 0],
       [0, 2, 0],
       [0, 0, 6]])

In [19]:
# матрица Грама ортонормированной системы векторов
x_norm=x/np.linalg.norm(x)
y_norm=y/np.linalg.norm(y)
z_norm=z/np.linalg.norm(z)
A_norm=np.array([x_norm,y_norm,z_norm])
print (A_norm, type(A_norm))

[[ 0.57735027  0.57735027  0.57735027]
 [ 0.70710678  0.         -0.70710678]
 [-0.40824829  0.81649658 -0.40824829]] <class 'numpy.ndarray'>


In [20]:
# матрица Грама ортонормированной системы векторов
A_norm@A_norm.T

array([[ 1.00000000e+00, -1.77961928e-17,  1.66584120e-17],
       [-1.77961928e-17,  1.00000000e+00, -2.45142679e-17],
       [ 1.66584120e-17, -2.45142679e-17,  1.00000000e+00]])

In [21]:
# ортонормированные системы рулят! :)
np.round(A_norm@A_norm.T,1)

array([[ 1., -0.,  0.],
       [-0.,  1., -0.],
       [ 0., -0.,  1.]])

### Problem 1.

In [22]:
A=np.array( [ [5,-1,3,1,2] , [-2,8,5,-1,1] ] )
x=np.array( [1,2,3,4,5] )

#### Task 1.
Найдите произведение матрицы A и вектора x в том порядке, в котором их можно умножить. Координаты вектора введите через запятую (без пробела):

In [28]:
A@x

array([26, 30])

#### Task 2.
Найдите произведение матриц A и B в том порядке, в котором их можно умножить.
В ответ запишите элемент из 1 строки и 4 столбца

In [29]:
A=np.array( [ [1,9,8,5] , [3,6,3,2] , [3,3,3,3], [0,2,5,9], [4,4,1,2] ] )
B=np.array( [ [1,-1,0,1,1] , [-2,0,2,-1,1] ] )

In [30]:
A

array([[1, 9, 8, 5],
       [3, 6, 3, 2],
       [3, 3, 3, 3],
       [0, 2, 5, 9],
       [4, 4, 1, 2]])

In [31]:
B

array([[ 1, -1,  0,  1,  1],
       [-2,  0,  2, -1,  1]])

In [34]:
C = B@A

In [35]:
C

array([[  2,   9,  11,  14],
       [  8, -10, -14, -11]])

In [36]:
C[0, 3]

14

#### Task 3.
Найдите матрицу Грама системы векторов x, y, z. Введите все элементы этой матрицы через запятую (без пробела), перечисляя построчно:

In [43]:
x=np.array([1,2,1,0,4])
y=np.array([2,1,-1,1,0])
z=np.array([-1,1,-1,0,0])

In [51]:
A = np.array([x, y, z])

In [52]:
A

array([[ 1,  2,  1,  0,  4],
       [ 2,  1, -1,  1,  0],
       [-1,  1, -1,  0,  0]])

In [53]:
A.T

array([[ 1,  2, -1],
       [ 2,  1,  1],
       [ 1, -1, -1],
       [ 0,  1,  0],
       [ 4,  0,  0]])

In [54]:
A@A.T

array([[22,  3,  0],
       [ 3,  7,  0],
       [ 0,  0,  3]])

### Problem 4.
В салоне красоты «Феи ножниц» работает 8 стилистов: Аня, Борис, Вика, Галя, Дима, Егор, Женя и Юра.
В dataframe Count_DF содержится информация по количеству услуг, оказанных каждым стилистом за апрель.
В dataframe Price_DF содержится информация по стоимости услуг у каждого стилиста в тысячах рублей.

In [57]:
import pandas as pd
Count_DF = pd.DataFrame({'Женские стрижки': [10, 2, 12, 4, 6, 10, 22, 7], 
                                'Мужские стрижки': [5, 21, 12, 8, 25, 3, 1, 0], 
                                'Окрашивания':[12, 3, 0, 18, 27, 2, 4, 31],
                              'Укладка':[15, 25, 30, 14, 25, 17, 25, 31],
                                'Уход':[10, 6, 4, 5, 18, 12, 20, 28]
                                }, 
                               index=['Аня', 'Борис', 'Вика', 'Галя', 'Дима', 'Егор', 'Женя','Юра'])
Price_DF = pd.DataFrame({'Женские стрижки': [2, 1.8, 2, 1.8, 2.5, 5, 1.1, 4.5], 
                                'Мужские стрижки': [1.5, 2.5, 2, 1.2, 3.5, 5, 1, 4], 
                                'Окрашивания':[1, 1, 0, 2.8, 2, 3, 1.5, 2.5],
                              'Укладка':[0.8, 1, 0.5, 0.8, 1, 2, 0.5, 1],
                                'Уход':[1, 1, 2, 2, 1.5, 2.5, 1.7, 2] 
                                }, 
                               index=['Аня', 'Борис', 'Вика', 'Галя', 'Дима', 'Егор', 'Женя','Юра'])

In [58]:
Count_DF

Женские стрижки  Мужские стрижки  Окрашивания  Укладка  Уход
Аня                 10                5           12       15    10
Борис                2               21            3       25     6
Вика                12               12            0       30     4
Галя                 4                8           18       14     5
Дима                 6               25           27       25    18
Егор                10                3            2       17    12
Женя                22                1            4       25    20
Юра                  7                0           31       31    28

In [59]:
Price_DF

Женские стрижки  Мужские стрижки  Окрашивания  Укладка  Уход
Аня                2.0              1.5          1.0      0.8   1.0
Борис              1.8              2.5          1.0      1.0   1.0
Вика               2.0              2.0          0.0      0.5   2.0
Галя               1.8              1.2          2.8      0.8   2.0
Дима               2.5              3.5          2.0      1.0   1.5
Егор               5.0              5.0          3.0      2.0   2.5
Женя               1.1              1.0          1.5      0.5   1.7
Юра                4.5              4.0          2.5      1.0   2.0

#### Task 4
Найдите вектор выручки Бориса. Введите координаты вектора через запятую (без пробела): 

In [67]:
C = Count_DF.values
P = Price_DF.values
I = C * P

In [71]:
I

array([[20. ,  7.5, 12. , 12. , 10. ],
       [ 3.6, 52.5,  3. , 25. ,  6. ],
       [24. , 24. ,  0. , 15. ,  8. ],
       [ 7.2,  9.6, 50.4, 11.2, 10. ],
       [15. , 87.5, 54. , 25. , 27. ],
       [50. , 15. ,  6. , 34. , 30. ],
       [24.2,  1. ,  6. , 12.5, 34. ],
       [31.5,  0. , 77.5, 31. , 56. ]])

In [68]:
I[1]

array([ 3.6, 52.5,  3. , 25. ,  6. ])

#### Task 5.
Найдите вектор прибыли салона по стилистам. Если за каждую услугу стилисты платят определенную комиссию салону.
Вектор комиссий
``` python
com=[0.2, 0.2, 0.3, 0.1, 0.1]
```
Введите координаты вектора через запятую (без пробела): 

In [69]:
com = np.array([0.2, 0.2, 0.3, 0.1, 0.1])

In [73]:
com @ I.T

array([11.3 , 15.22, 11.9 , 20.6 , 41.9 , 21.2 , 11.49, 38.25])

#### Task 6. Найдите вектор прибыли стилистов 

In [75]:
res = np.ones(5) - com

In [76]:
res

array([0.8, 0.8, 0.7, 0.9, 0.9])

In [77]:
st_inc = res @ I.T

In [78]:
st_inc

array([ 50.2 ,  74.88,  59.1 ,  67.8 , 166.6 , 113.8 ,  66.21, 157.75])