In [1]:
import numpy as np

In [2]:
A = np.matrix('1, -5; 2, 2; 0, 3')
B = np.matrix('3, 1, 0; -1, 0, 2')

In [3]:
A

matrix([[ 1, -5],
        [ 2,  2],
        [ 0,  3]])

In [4]:
B

matrix([[ 3,  1,  0],
        [-1,  0,  2]])

In [5]:
A@B

matrix([[  8,   1, -10],
        [  4,   2,   4],
        [ -3,   0,   6]])

In [6]:
B@A

matrix([[  5, -13],
        [ -1,  11]])