In [1]:
import numpy as np

In [2]:
A = np.array([
    [1, 2],
    [-3, 1],
    [1, 2],
    [1, -1]
])

In [3]:
b = np.array([
    [1],
    [4],
    [5],
    [0]
])

In [4]:
Ag = A.T@A

In [5]:
Ag

array([[12,  0],
       [ 0, 10]])

In [7]:
Ag_ = np.linalg.inv(Ag)

In [8]:
Ag_

array([[0.08333333, 0.        ],
       [0.        , 0.1       ]])

In [11]:
ATb = A.T@b
ATb

array([[-6],
       [16]])

In [12]:
w = Ag_@ATb

In [13]:
w

array([[-0.5],
       [ 1.6]])