In [1]:
import numpy as np

#### Сложение и вычитание векторов

In [2]:
a = np.array([10, 8, 5, 1])

In [3]:
b = np.array([5, 15, 9, 7])

In [4]:
a + b

array([15, 23, 14,  8])

In [5]:
a - b

array([ 5, -7, -4, -6])

#### Умножение вектора на число

In [6]:
a = np.array([120, 45, 68])

In [7]:
omega = 0.2

In [8]:
omega * a

array([24. ,  9. , 13.6])

#### Task 3.
Доходы Алексея за три месяца составили , и тысяч рублей, его жены: , и тысяч рублей, а тёщи: , и тысячи евро.
Найдите вектор доходов тёщи в тыс. рублей, если курс евро составляет рубля.

Введите координаты полученного вектора через запятую (без пробела):

Найдите вектор суммарного дохода семьи в тыс. рублей по месяцам.

Введите координаты полученного вектора через запятую (без пробела):

In [9]:
a = np.array([120, 150, 90])
b = np.array([130, 130, 130])
c = np.array([2, 3, 2.5])

In [10]:
72*c

array([144., 216., 180.])

In [11]:
a + b + 72*c

array([394., 496., 400.])