In [1]:
import numpy as np

In [2]:
s = np.array([33, 65, 50, 45])

In [3]:
s

array([33, 65, 50, 45])

In [4]:
s[2]

50

In [5]:
len(s)

4

#### np.array examples.

In [8]:
x = np.array([1, 2, 3])
x.ndim

1

In [9]:
y = np.zeros((2, 3, 4))
y.ndim

3

In [13]:
x = np.array([(1,2),(3,4)],dtype=[('a','<i4'),('b','<i4')])
x

array([(1, 2), (3, 4)], dtype=[('a', '<i4'), ('b', '<i4')])

In [14]:
x[0]

(1, 2)

In [15]:
x[0][1]

2

In [17]:
np.array(np.mat('1 2; 3 4'))

array([[1, 2],
       [3, 4]])

In [18]:
np.array(np.mat('1 2; 3 4'), subok=True)

matrix([[1, 2],
        [3, 4]])

#### Python task.

In [6]:
apartment = np.array([59.50, 31.40, 19, 22, 60550, 2])

In [19]:
# вычислим долю жилой площади в квартире
share_living_space = apartment[1]/apartment[0]

In [20]:
apartment = np.delete(apartment, [0, 1])

In [21]:
apartment = np.append(apartment, share_living_space)

In [22]:
apartment

array([1.90000000e+01, 2.20000000e+01, 6.05500000e+04, 2.00000000e+00,
       5.27731092e-01])

#### Task 1.
Введите значение получившегося нового признака share_living_space. Используйте код и ссылки на документацию из описания квартиры. Ответ округлите до 2-х заков после точки. 

In [25]:
print(f'share_living_space={apartment[4]:.2f}')

share_living_space=0.53


#### Task 2.
Укажите размерность конечного массива apartment после преобразования (ввода новой переменной и удаления старых). Ответ является целым числом.

In [27]:
print(len(apartment))

5


#### Task 3.
Пусть дан вектор в python вида:
``` python
t = np.array([12, 14, 17, 19, 24, 28, 31, 31, 27, 22, 17, 13])
```
содержащий информацию о средней температуре воздуха (в градусах Цельсия) в Риме с января по декабрь включительно.
Выберите неверное утверждение:
* t5=28C средняя температура воздуха в июне
* Минимальная средняя температура воздуха в Риме достигается в январе
* t2 = 17C средняя температура воздуха в феврале
* Максимальная средняя температура воздуха в Риме достигается в июле 

In [29]:
t = np.array([12, 14, 17, 19, 24, 28, 31, 31, 27, 22, 17, 13])

In [31]:
t[5] == 28

True

In [33]:
t.argmin() == 0

True

In [36]:
t[1] == 17

False

In [35]:
t.argmax() == 6

True